modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="laundrysmiscmod"
version="1.0.0"
displayName="Laundry's Misc Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Admin, MCreator"

[[dependencies.laundrysmiscmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



